<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class SetupLaragonVirtualHost extends Command
{
    protected $signature = 'laragon:setup-vhost 
                            {--domain=example.test : Base domain for wildcard}
                            {--path= : Laragon Apache config path (auto-detect if not provided)}';

    protected $description = 'Setup Laragon wildcard virtual host for tenant domains';

    public function handle()
    {
        $baseDomain = $this->option('domain') ?: config('saas.base_domain', 'example.test');
        $configPath = $this->option('path');

        // Auto-detect Laragon Apache config path
        if (!$configPath) {
            $configPath = $this->detectLaragonConfigPath();
        }

        if (!$configPath || !File::exists($configPath)) {
            $this->error('Laragon Apache config file not found!');
            $this->info('Please provide the path manually:');
            $this->info('php artisan laragon:setup-vhost --path="C:\\laragon\\bin\\apache\\apache-2.4.x\\conf\\extra\\httpd-vhosts.conf"');
            return 1;
        }

        $this->info("Found Laragon config: {$configPath}");

        // Read current config
        $config = File::get($configPath);

        // Check if wildcard vhost already exists
        $wildcardDomain = '*.' . $baseDomain;
        if (str_contains($config, $wildcardDomain)) {
            $this->warn("Wildcard virtual host for {$wildcardDomain} already exists!");
            if (!$this->confirm('Do you want to update it?', false)) {
                return 0;
            }
            // Remove existing wildcard vhost
            $config = preg_replace(
                '/<VirtualHost\s+\*:80>.*?ServerName\s+' . preg_quote($wildcardDomain, '/') . '.*?<\/VirtualHost>/s',
                '',
                $config
            );
        }

        // Generate virtual host configuration
        $publicPath = public_path();
        $vhostConfig = $this->generateVirtualHostConfig($wildcardDomain, $publicPath);

        // Append to config file
        $config .= "\n\n" . $vhostConfig;

        // Backup original config
        $backupPath = $configPath . '.backup.' . date('Y-m-d_His');
        File::copy($configPath, $backupPath);
        $this->info("Backup created: {$backupPath}");

        // Write new config
        File::put($configPath, $config);
        $this->info("Virtual host configuration added successfully!");

        $this->newLine();
        $this->info('Next steps:');
        $this->line('1. Restart Apache in Laragon (Menu > Apache > Restart)');
        $this->line('2. Test with: http://test10.' . $baseDomain . '/admin');

        return 0;
    }

    protected function detectLaragonConfigPath(): ?string
    {
        $possiblePaths = [
            'C:\\laragon\\bin\\apache\\apache-2.4.x\\conf\\extra\\httpd-vhosts.conf',
            'C:\\laragon\\bin\\apache\\apache-2.4\\conf\\extra\\httpd-vhosts.conf',
            'C:\\laragon\\apache\\conf\\extra\\httpd-vhosts.conf',
        ];

        // Try to find Apache version dynamically
        $laragonBinPath = 'C:\\laragon\\bin\\apache';
        if (is_dir($laragonBinPath)) {
            $apacheDirs = glob($laragonBinPath . '\\apache-*', GLOB_ONLYDIR);
            if ($apacheDirs) {
                foreach ($apacheDirs as $apacheDir) {
                    $vhostPath = $apacheDir . '\\conf\\extra\\httpd-vhosts.conf';
                    if (file_exists($vhostPath)) {
                        return $vhostPath;
                    }
                }
            }
        }

        // Try predefined paths
        foreach ($possiblePaths as $path) {
            if (file_exists($path)) {
                return $path;
            }
        }

        return null;
    }

    protected function generateVirtualHostConfig(string $domain, string $documentRoot): string
    {
        return <<<EOF
# Wildcard Virtual Host for Tenant Domains
# Auto-generated by: php artisan laragon:setup-vhost
# Generated at: {$this->getCurrentTimestamp()}

<VirtualHost *:80>
    ServerName {$domain}
    ServerAlias {$domain}
    DocumentRoot "{$documentRoot}"
    
    <Directory "{$documentRoot}">
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    
    # Logging
    ErrorLog "C:/laragon/logs/apache/{$domain}-error.log"
    CustomLog "C:/laragon/logs/apache/{$domain}-access.log" combined
</VirtualHost>
EOF;
    }

    protected function getCurrentTimestamp(): string
    {
        return date('Y-m-d H:i:s');
    }
}
